modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "GNU GENERAL PUBLIC LICENSE - v3"

[[mods]]
modId = "slskills"
version = "1.0"
displayName = "VSunlit Skills"
description = ""
authors = "antthLuca"
